config/routes.rb
Rails.application.routes.draw do

   get '/missions' => 'missions#index'

  resources :missions

end

app/models/mission.rb
class Mission < ActiveRecord::Base
  def index
    @mission = Mission.all
    # takes all the planets from db and stores as instance variable.
    # come back as array of objects
    
      end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/missions_controller.rb
class MissionsController < ApplicationController
  
  # Params is talking to the database as well
# but here we are defining what is going to happen when our 
# functions are called.  Function is called, controller handles
# the call or action to the database and sends back the response.


  def index
    @missions = Mission.all
  end
  # this gets all this items from db as object?
  def show
    @mission = Mission.find(params[:id])
    end
 # this gets the id as a param from the url and returns that row as object
  def new
    @mission = Mission.new

    # make a new one

  end

  def create
    Mission.create(mission_params)
    redirect_to(missions_path)
  end

  def destroy
    mission = Mission.find(params[:id])
    mission.destroy
    redirect_to(missions_path)
  end

  def edit

    @mission =Mission.find(params[:id])
    

  end

  def update
    Mission.find(params[:id]).update(mission_params)
    redirect_to(missions_path)
  end


  def wiki
     @page = Wikipedia.find('Getting Things Done') 
   end

















    private

    def mission_params
      params.require(:mission).permit(:name, :image, :outcome, :objective)
    end






end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ApolloApp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/missions/edit.html.erb
<%= form_for @mission do |f| %>

 <%= f.label :name %>
 <%= f.text_field :name %>

 <%= f.label :image %>
 <%= f.text_field :image %>

 <%= f.text_field :outcome %>
 <% f.label :outcome %>

 <%= f.text_field :objective %>
 <% f.label :objective %>

 <%= f.submit 'Update Mission' %>
<% end %>

app/views/missions/index.html.erb
<h3> This is the Mission index page </h3>


<% page = Wikipedia.find('Getting Things Done') %>
<h1> <%= page.title %> </h1>



<div class ='list-group'>

  <% @missions.each do | mission | %>
  <div class="list-group-item">
  <ul class = "mission">

  <li> <%= link_to(mission.name, mission_path(mission.id)) %> </li>
  <li> <%= link_to('Delete', mission_path(mission.id), method: :delete) %></li>

  <%= link_to('Edit', edit_mission_path(mission.id)) %>
  <!-- command is edit, mission path is taken from mission.id
  which we can call because we are in instance of an @mission
  from the .each loop above -->
  </ul>
  </div>
  <% end %>
  </div>

app/views/missions/new.html.erb
<%= form_for @mission do |f| %>

 <%= f.label :name %>
 <%= f.text_field :name %>

 <%= f.label :image %>
 <%= f.text_field :image %>

 <%= f.text_field :outcome %>
 <% f.label :outcome %>

 <%= f.text_field :objective %>
 <% f.label :objective %>

 <%= f.submit 'Create Mission' %>
<% end %>

app/views/missions/show.html.erb
<div class-"mission-info">
<%= @mission.name %>
<%= image_tag(@mission.image, width: 200) %>
<%= @mission.objective %>
<%= @mission.mass %>
<%= @mission.outcome %>
</div>